export const TECH_MAPPING = {
    Python: "black",
    ReactJs: "green",
    JavaScript: "yellow",
    Redux: "blue",
    HTML: "grey",
    CSS: "olive",
    SCSS: "olive",
    Express: "tomato",
    Mongoose: "orange",
    Bootstrap: "#5b9ddf",
    Material: "#5b9ddf",
    C: "#5b9ddf",
    "C++": "#5b9ddf",
    MongoDB: "greenyellow",
    MySQL: "purple",
    Git: "red",
};
