export const TECH_MAPPING = {
    Python: "red",
    ReactJs: "green",
    JavaScript: "yellow",
    Redux: "blue",
    HTML: "grey",
    CSS: "olive",
    SCSS: "olive",
    Express: "tomato",
    Mongoose: "greenyellow",
    Bootstrap: "#5b9ddf",
    Material: "#5b9ddf",
    C: "#5b9ddf",
    "C++": "#5b9ddf",
    MongoDB: "greenyellow",
    MySQL: "purple",
    Git: "maroon",
    VSCode: "black",
    Postman: "orange",
    Java: "brown",
    PostgreSQL: "magenta",
};
